import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// ローカル設定 (env.json) があればそこからVaultパスを解決、なければカレントディレクトリ
let outdir = "./";
if (fs.existsSync("env.json")) {
  try {
    const env = JSON.parse(fs.readFileSync("env.json", "utf-8"));
    if (env.vaultPath) {
      outdir = path.join(env.vaultPath, ".obsidian", "plugins", "mumbler");
    }
  } catch (err) {
    console.warn("[esbuild] Could not parse env.json, defaulting output to current directory.", err);
  }
}

// ビルド完了時に manifest.json を出力先プラグインフォルダへ自動コピーするプラグイン
const copyManifestPlugin = {
  name: "copy-manifest",
  setup(build) {
    build.onEnd(() => {
      // 出力先がカレントディレクトリでない場合のみコピー
      if (path.resolve(outdir) !== path.resolve("./")) {
        try {
          if (!fs.existsSync(outdir)) {
            fs.mkdirSync(outdir, { recursive: true });
          }
          fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
          console.log(`[esbuild] Copied manifest.json to ${outdir}`);

          if (fs.existsSync("styles.css")) {
            fs.copyFileSync("styles.css", path.join(outdir, "styles.css"));
            console.log(`[esbuild] Copied styles.css to ${outdir}`);
          }
        } catch (err) {
          console.error(`[esbuild] Failed to copy manifest.json:`, err);
        }
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(outdir, "main.js"),
  plugins: [copyManifestPlugin],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
} else {
  await context.watch();
  console.log(`[esbuild] Watching for changes... Target: ${outdir}`);
}
